api/urls.py
from django.urls import path,include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'customer', views.CustomerViewset)
router.register(r'manager', views.ManagerViewset)
router.register(r'booking', views.BookingViewset)
router.register(r'rooms', views.RoomsViewset)
urlpatterns = [
    path('', include(router.urls))
]

manager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('manager/dashboard/', views.dashboard, name='manager_dashboard'),
    path('manager/add/', views.add_room, name='add-room'),
    path('manager/add-room/update/<int:room_no>/', views.update_room, name="update-room"),
]

myHotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Hotel Admin'
admin.site.index_title = 'Manager Admin page'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('booking.urls')),
    path('api/', include('api.urls')),
    path('customers/', include('customers.urls')),
    path('', include('manager.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
          name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
          name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
          name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
          name='password_reset_complete'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models
from accounts.models import Manager, Customer
from PIL import Image
from django.core.files.storage import default_storage as storage

class News(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = "News"

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone_no = models.CharField(max_length=100)
    message = models.TextField(max_length=5000)

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name_plural = "Contact"

class Rooms(models.Model):
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    room_no = models.CharField(max_length=5)
    room_type = models.CharField(max_length=50)
    is_available = models.BooleanField(default=True)
    price = models.FloatField(default=1000.00)
    no_of_days_advance = models.IntegerField()
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    image = models.ImageField(default='room.jpg', upload_to='User/images/', null=False, blank=False)


    def __str__(self):
        return "Room No: "+ str(self.id)

    class Meta:
        verbose_name_plural = "Rooms"

    def save(self, *args, **kwargs):
        if not self.room_no and self.room_type:
            return

        super(Rooms, self).save()
        if self.image:
            size = 300, 300
            image = Image.open(self.image)
            image.thumbnail(size, Image.ANTIALIAS)
            fh = storage.open(self.image.name, "w")
            format = "png"
            image.save(fh, format)
            fh.close()


class Booking(models.Model):
    room_no = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    user_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    start_day = models.DateField(auto_now=False, auto_now_add=False)
    end_day = models.DateField(auto_now=False, auto_now_add=False)
    amount = models.FloatField()
    booked_on = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return "Booking ID: " + str(self.id)

    class Meta:
        verbose_name_plural = "Booking"

    @property
    def is_past_due(self):
        return self.start_day > self.end_day

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.apps import apps
Manager = apps.get_model('accounts', 'Manager')
Booking = apps.get_model('booking', 'Booking')
Rooms = apps.get_model('booking', 'Rooms')
import datetime
from django.contrib import messages
from datetime import date


def dashboard(request):
    if not request.session.get('username', None):
        return redirect('manager_login')
    if request.session.get('username', None) and request.session.get('type', None) == 'customer':
        return redirect('user_dashboard')

    if request.session.get('username', None) and request.session.get('type', None) == 'manager':
        username = request.session['username']
        data = Manager.objects.get(username=username)
        room_data = data.rooms_set.all()
        booked = room_data.filter(is_available=False).count()

        context = {
           "room_data": room_data,
           "manager": data,
           "booked": booked
        }
        return render(request, "manager/index.html", context)

    else:
        return redirect("manager_login")


def add_room(request):
    if not request.session.get('username', None):
        return redirect('manager_login')
    if request.session.get('username', None) and request.session.get('type', None) == 'customer':
        return redirect('user_dashboard')
    if request.method == "GET":
        return render(request, "manager/add-room.html", {})
    else:
        room_no = request.POST['room_no']
        room_type = request.POST['room_type']
        price = request.POST['price']
        image = request.FILES.get('image',None)
        no_of_days_advance = request.POST['no_of_days_advance']
        start_day = request.POST['start_day']
        error = []
        if(len(room_no)<1):
            messages.warning(request, "Room No Field must be atleast 3 digit like 100.")
        if(len(room_type)<5):
            error.append(1)
            messages.warning(request, "Select a valid Room Type.")
        if(len(price)<=2):
            error.append(1)
            messages.warning(request, "Please enter price")
        if(len(no_of_days_advance)<1):
            error.append(1)
            messages.warning(request, "Please add valid no of days a user can book room in advance.")
        if(len(start_day)<3):
            error.append(1)
            messages.warning(request, "Please add the starting day")
        if(not len(error)):
            manager = request.session['username']
            manager = Manager.objects.get(username=manager)
            room = Rooms(room_no=room_no, room_type=room_type, price=price, no_of_days_advance=no_of_days_advance,
                         start_date=datetime.datetime.strptime(start_day, "%d %B, %Y").date(),
                         image=image, manager=manager)
            room.save()
            messages.success(request, "Room Added Successfully")
            return redirect('manager_dashboard')
        else:
            return redirect('/manager/add/')


def update_room(request,room_no):
    if not request.session.get('username', None):
        return redirect('manager_login')
    if request.session.get('username', None) and request.session.get('type', None) == 'customer':
        return redirect('user_dashboard')
    room = Rooms.objects.get(room_no=room_no)
    if request.method == "GET":
        return render(request, "manager/edit-room.html", {"room": room})
    else:
        price = request.POST['price']
        no_of_days_advance = request.POST['no_of_days_advance']
        error = []
        if(len(price)<=2):
            error.append(1)
            messages.warning(request, "Please enter correct price")
        if(len(no_of_days_advance)<1):
            error.append(1)
            messages.warning(request, "Please add valid no of days a user can book room in advance.")
        if(not len(error)):
            manager = request.session['username']
            manager = Manager.objects.get(username=manager)
            room.price = price
            room.no_of_days_advance = no_of_days_advance
            room.save()
            messages.success(request, "Room Data Updated Successfully")
            return redirect('manager_dashboard')
        else:
            return redirect('/manager/add-room/update/' + room.room_no, {"room": room})

templates/manager/add-room.html
{% extends 'others/base.html'%}

{% load static %}
{% block content %}

<body>
  <div>
    <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
        <fieldset class="field">
             <div class="join">Add Room</div>
             <br>
              <div class="form-group">
                <label for="image" class="col-form-label">Image:</label>
                  <br>
                <input type="file" name="image">
              </div>
              <div class="form-group">
                <label for="room_type" class="col-form-label">Room_type:</label>
                <select class="form-control" name="room_type">
                    <option value="Single Room">Single Room</option>
                    <option value="Double Room">Double Room</option>
                    <option value="Deluxe Room">Deluxe Room</option>
                    <option value="Super Deluxe Room">Super Deluxe Room</option>
                </select>
              </div>
              <div class="form-group">
                 <label for="room_no" class="col-form-label">Room_no:</label>
                 <input type="text" name="room_no" class="form-control">
              </div>
              <div class="form-group">
                 <label for="price" class="col-form-label">Price:</label>
                 <input type="text" name="price" class="form-control">
              </div>
              <div class="form-group">
                 <label for="no_of_days_advance" class="col-form-label">Duration:</label>
                 <input type="text" name="no_of_days_advance" class="form-control">
              </div>
               <div class="form-group">
                 <label for="start_day" class="col-form-label">Start_day:</label>
                 <input type="text" name="start_day" class="form-control datepicker">
              </div>
           <div class="sign-in">
             <button type="submit" class="btn btn-primary">Add room</button>
           </div>
           <br>
         </fieldset>
    </form>
  </div>
</body>
<script>
     $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false // Close upon selecting a date,
  });

</script>
<h1 style="margin-bottom: 3%;"></h1>
{% include 'others/footer.html' %}
{% endblock %}

templates/manager/edit-room.html
{% extends 'others/base.html'%}

{% load static %}
{% block content %}

<body>
  <div>
      <h3 style="margin-bottom: 3%;"></h3>
    <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
        <fieldset class="field">
             <div class="join">Updating the Data for Room No: {{room.room_no}}</div>
              <div class="form-group">
                 <label for="price" class="col-form-label">Price:</label>
                 <input type="text" name="price" class="form-control" value="{{ room.price }}">
              </div>
              <div class="form-group">
                 <label for="no_of_days_advance" class="col-form-label">Duration:</label>
                 <input type="text" name="no_of_days_advance" class="form-control" value="{{room.no_of_days_advance}}">
              </div>
           <div class="sign-in">
             <button type="submit" class="btn btn-primary">Update room</button>
           </div>
           <br>
         </fieldset>
    </form>
  </div>
</body>

{% endblock %}

templates/manager/index.html
{% extends 'others/base1.html'%}
{% load static %}
{% load humanize %}
{% block content %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"  rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Shadows+Into+Light&display=swap" rel="stylesheet">
  <h1 style="margin-bottom: 5%;"></h1>
  <div class="room-body">
     <div class="room-head">
      <div class="room-top">
         <div class="room-sheet1">
            <div class="roomy">
                <h5>Occupied Rooms Status</h5>
                <h3>
                {{ booked }}
                </h3>
            </div>
         </div>
         <div class="room-sheet1">
            <div class="roomy">
                <h5>Total Rooms to manage</h5>
                <h3>
                {{ room_data.count }}
                </h3>
            </div>
         </div>
      </div>
     </div>
       <div class="babe"><a class="btn btn-primary" href="{% url 'add-room' %}">Add More Rooms</a></div>
        <h3 class="table-head">Room Status</h3>
    {% if room_data %}
        <div class="table-responsive">
             <table class="table table-striped table-dark">
                <thead>
                  <tr>
                      <th scope="col">Room No</th>
                      <th scope="col">Room Type</th>
                      <th scope="col">Price</th>
                      <th scope="col">Customer Name</th>
                      <th scope="col">Booked On</th>
                      <th scope="col">Booking Data</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    {% for room in room_data%}
                      <tr>
                        <td>{{room.room_no}}</td>
                        <td>{{room.room_type}}</td>
                        <td>${{room.price}}</td>
                        {% with data=room.booking_set.all.0 %}
                        <td><a href="/customers/detail/{{data.user_id.id}}/{{data.id}}">{{data.user_id.username}}</a></td>
                        <td>{{data.booked_on | naturaltime }}</td>
                        <td>
                        {% if room.is_available %}
                            Available
                        {% else %}
                             {{ data.start_day }} to {{ data.end_day }}
                        {% endif %}
                        </td>
                        <td><a class="btn btn-primary" href="/manager/add-room/update/{{room.room_no}}"><i class="fas fa-edit"></i></a></td>
                        <td><a class="btn btn-danger" href="/room-delete/{{ room.id }}"><i class="fas fa-trash"></i></a></td>
                        {% endwith %}
                      </tr>
                    {% endfor %}
                </tbody>
             </table>
        </div>
    {% else %}
       <p>Sorry no rooom has been added by you, please add a room now <a href="{% url 'add-room' %}">Here</a></p>
    {% endif %}
  </div>
<h1 style="margin-bottom: 3%;"></h1>
{% if room_data %}
  {% include 'others/footer.html' %}
{% else %}
   <h1 style="margin-bottom: 1%;"></h1>
{% endif %}
{% endblock %}